// <auto-generated />
namespace ProductsDistribution.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Unit_field_added_to_productTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Unit_field_added_to_productTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201803011315568_Unit_field_added_to_productTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
