// <auto-generated />
namespace ProductsDistribution.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddCutDropdown_Menu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCutDropdown_Menu));
        
        string IMigrationMetadata.Id
        {
            get { return "201804201712549_AddCutDropdown_Menu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
