// <auto-generated />
namespace ProductsDistribution.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Move_ArriveDate_From_Announcement_To_Announcement2Product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Move_ArriveDate_From_Announcement_To_Announcement2Product));
        
        string IMigrationMetadata.Id
        {
            get { return "201804151412266_Move_ArriveDate_From_Announcement_To_Announcement2Product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
