// <auto-generated />
namespace ProductsDistribution.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_datetime2_format : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_datetime2_format));
        
        string IMigrationMetadata.Id
        {
            get { return "201805150907551_remove_datetime2_format"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
