// <auto-generated />
namespace ProductsDistribution.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DateTime2_Format_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DateTime2_Format_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201805141506210_DateTime2_Format_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
