// <auto-generated />
namespace ProductsDistribution.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Index_Added_to_ProducerName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Index_Added_to_ProducerName));
        
        string IMigrationMetadata.Id
        {
            get { return "201802250702155_Index_Added_to_ProducerName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
